"""add language to user

Revision ID: 103c81c2bbf7
Revises: bb7687bb6cc7
Create Date: 2025-12-23 21:00:36.301755

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "103c81c2bbf7"
down_revision: str | Sequence[str] | None = "bb7687bb6cc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("language_code", sa.String(length=2), server_default="ru", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "language_code")
    # ### end Alembic commands ###
