"""add variants to card model

Revision ID: bb7687bb6cc7
Revises: 1edac2526f70
Create Date: 2025-12-23 13:59:26.783426

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb7687bb6cc7"
down_revision: str | Sequence[str] | None = "1edac2526f70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("card_type", sa.String(length=20), nullable=False))
    op.add_column("cards", sa.Column("variant_1", sa.Text(), nullable=True))
    op.add_column("cards", sa.Column("variant_2", sa.Text(), nullable=True))
    op.add_column("cards", sa.Column("variant_3", sa.Text(), nullable=True))
    op.add_column("cards", sa.Column("variant_4", sa.Text(), nullable=True))
    op.add_column("cards", sa.Column("correct_variant", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "correct_variant")
    op.drop_column("cards", "variant_4")
    op.drop_column("cards", "variant_3")
    op.drop_column("cards", "variant_2")
    op.drop_column("cards", "variant_1")
    op.drop_column("cards", "card_type")
    # ### end Alembic commands ###
